# -*- coding: utf-8 -*-
"""crop_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157M9ZGJOat1u-gtyIC4u-T8sO_wFt2H7
"""



"""# Task
Analyze the dataset in "/content/9ef84268-d588-465a-a308-a864a43d0070.csv", build a linear regression model to predict crop prices, and export the model for local use and web application integration.

## Load the data

### Subtask:
Load the dataset from "/content/9ef84268-d588-465a-a308-a864a43d0070.csv" into a pandas DataFrame.

**Reasoning**:
The first step is to load the data into a pandas DataFrame for analysis.
"""

import pandas as pd

df = pd.read_csv('/content/9ef84268-d588-465a-a308-a864a43d0070.csv')
display(df.head())

"""## Explore the data

### Subtask:
Analyze the dataset to understand its structure, identify relevant features, and check for missing values or outliers.

**Reasoning**:
Display column names and data types, generate descriptive statistics for numerical columns, and check for missing values.
"""

display(df.info())
display(df.describe())
display(df.isnull().sum())

"""**Reasoning**:
Examine unique values and their counts for categorical columns.


"""

for col in ['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade', 'Arrival_Date']:
    display(f"Column: {col}")
    display(df[col].value_counts().head())
    display(f"Number of unique values: {df[col].nunique()}")

"""## Preprocess the data

### Subtask:
Clean and preprocess the data by handling missing values, encoding categorical features, and scaling numerical features as needed.

**Reasoning**:
Drop the 'Arrival_Date' column, identify categorical columns, apply one-hot encoding, and display the first few rows of the processed DataFrame to verify the changes.
"""

# Drop the 'Arrival_Date' column
df = df.drop('Arrival_Date', axis=1)

# Identify categorical columns
categorical_cols = ['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade']

# Apply one-hot encoding
df_processed = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Display the first few rows of the processed DataFrame
display(df_processed.head())

"""## Split the data

### Subtask:
Split the dataset into training and testing sets for model development and evaluation.

## Summary:

### Data Analysis Key Findings

* The dataset contains 17628 entries and 10 columns, including categorical features like 'State', 'District', 'Market', 'Commodity', 'Variety', 'Grade', and numerical price data ('Min\_x0020\_Price', 'Max\_x0020\_Price', 'Modal\_x0020\_Price').
* There are no missing values in the dataset.
* Numerical columns show a wide range of values, indicating potential outliers.
* The 'Arrival\_Date' column has only one unique value ('11-09-2025'), rendering it non-informative for time-based price prediction and was subsequently dropped.
* Categorical features were successfully one-hot encoded, significantly increasing the number of features to 2670.
* The dataset was split into training (80%, 14102 samples) and testing (20%, 3526 samples) sets.
* A linear regression model was trained on the preprocessed data.
* The model achieved a Mean Squared Error (MSE) of approximately 329999.37 and an R-squared (R2) score of approximately 0.9896 on the testing data, suggesting a strong fit.
* The trained linear regression model was successfully exported to a file named 'linear\_regression\_model.pkl' using the `joblib` library.

### Insights or Next Steps

* Investigate potential outliers in the price columns and their impact on model performance.
* Explore alternative regression models or feature engineering techniques to potentially improve model performance further, although the current R2 score is very high.
"""

import joblib
import pandas as pd

# Define the filename
filename = 'linear_regression_model.pkl'

# Load the model from the file
loaded_model = joblib.load(filename)

# Example of how to use the loaded model to make a prediction
# Create a sample input DataFrame with the same columns as the training data
# Replace with actual data for prediction
sample_input = X_test.iloc[0].copy()
sample_input = sample_input.to_frame().T # Convert Series to DataFrame

# Make a prediction using the loaded model
predicted_price = loaded_model.predict(sample_input)

print(f"Predicted Modal Price: {predicted_price[0]:.2f}")

"""To integrate this into a local web application, you would typically use a web framework like Flask or Django. Here's a conceptual outline using Flask:

1.  **Set up a Flask application**: Create a Flask app.
2.  **Load the model**: Load the `linear_regression_model.pkl` file when the application starts.
3.  **Create an endpoint**: Define an API endpoint (e.g., `/predict`) that accepts input data for prediction.
4.  **Receive and process input**: In the endpoint, receive the input data (e.g., as JSON), preprocess it to match the format the model expects (including one-hot encoding the categorical features with the same columns used during training), and then use the loaded model to make a prediction.
5.  **Return the prediction**: Return the predicted price as a JSON response.

**Important Considerations for Web Integration:**

*   **Preprocessing**: Ensure the input data in your web application is preprocessed exactly the same way as your training data (handling categorical features, etc.). You'll need to save the list of columns from your `X_train` to ensure the new data has the same structure after one-hot encoding.
*   **Dependencies**: Make sure your web environment has the necessary libraries installed (pandas, scikit-learn, joblib).
*   **Scalability**: For a production web application, consider more robust ways to serve your model, such as using a dedicated model serving framework or cloud services.

**Reasoning**:
Split the processed data into features (X) and target (y) and then split these into training and testing sets.
"""

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df_processed.drop('Modal_x0020_Price', axis=1)
y = df_processed['Modal_x0020_Price']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Verify the shapes of the resulting sets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""## Build the linear regression model

### Subtask:
Train a linear regression model using the training data to predict crop prices.

**Reasoning**:
Train a linear regression model using the training data.
"""

from sklearn.linear_model import LinearRegression

# Instantiate a LinearRegression model
model = LinearRegression()

# Fit the model to the training data
model.fit(X_train, y_train)

"""## Evaluate the model

### Subtask:
Evaluate the performance of the trained model using appropriate metrics on the testing data.

**Reasoning**:
Evaluate the performance of the trained model using appropriate metrics on the testing data.
"""

from sklearn.metrics import mean_squared_error, r2_score

# Use the trained model to make predictions on the testing features
y_pred = model.predict(X_test)

# Calculate the Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)

# Calculate the R-squared score
r2 = r2_score(y_test, y_pred)

# Print the calculated MSE and R-squared score
print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2) Score: {r2}")

"""## Export the model

### Subtask:
Save the trained linear regression model to a file format that can be used locally and integrated into a web application.

**Reasoning**:
Save the trained linear regression model to a file using joblib.
"""

import joblib

# Define the filename
filename = 'linear_regression_model.pkl'

# Save the trained model to the file
joblib.dump(model, filename)

print(f"Model successfully saved to {filename}")

"""## Integrate the model

### Subtask:
Explain how to integrate the exported model into a web application for making predictions.

## Summary:

### Data Analysis Key Findings

*   The dataset contains 17628 entries and 10 columns, including categorical features like 'State', 'District', 'Market', 'Commodity', 'Variety', 'Grade', and numerical price data ('Min\_x0020\_Price', 'Max\_x0020\_Price', 'Modal\_x0020\_Price').
*   There are no missing values in the dataset.
*   Numerical columns show a wide range of values, indicating potential outliers.
*   The 'Arrival\_Date' column has only one unique value ('11-09-2025'), rendering it non-informative for time-based price prediction and was subsequently dropped.
*   Categorical features were successfully one-hot encoded, significantly increasing the number of features to 2670.
*   The dataset was split into training (80%, 14102 samples) and testing (20%, 3526 samples) sets.
*   A linear regression model was trained on the preprocessed data.
*   The model achieved a Mean Squared Error (MSE) of approximately 329999.37 and an R-squared (R2) score of approximately 0.9896 on the testing data, suggesting a strong fit.
*   The trained linear regression model was successfully exported to a file named 'linear\_regression\_model.pkl' using the `joblib` library.

### Insights or Next Steps

*   Investigate potential outliers in the price columns and their impact on model performance.
*   Explore alternative regression models or feature engineering techniques to potentially improve model performance further, although the current R2 score is very high.
"""